### ISSUE TITLE
Here are some hints that can help people get started

### ISSUE THREAD

**Issue by ryancwalsh** [BitbucketAPI/Client#14]
Thanks so much for offering this library! It's a huge help.

It took me quite a while to get started. I was really confused at the beginning and was getting misleading error messages.  I jotted some notes down that you might want to use in some of your Readme docs to help people get moving easier.

https://gist.github.com/ryancwalsh/6f61ab68d8331e5810c955fa2700ea11

**Comment by GrahamCampbell** [comment]
Thanks for this. What went wrong for you when you tried to use the Laravel package?

**Comment by ryancwalsh** [comment]
I couldn't remember but just clicked the link above and saw line 12 mentions a misleading error message, so that was probably the problem / confusion I faced at the time: https://gist.github.com/ryancwalsh/6f61ab68d8331e5810c955fa2700ea11#file-downloadbitbucketissues-php-L12

**Comment by GrahamCampbell** [comment]
Hmm, I could not recommend the approach in the example code. We already have a paginator, and a working Laravel package used by hundreds of people.

**Comment by GrahamCampbell** [comment]
> When I tried granting access to just Issues, I got this misleading error: Symfony\Component\Debug\Exception\FatalThrowableError  : strtok() expects parameter 1 to be string, array given

What was the full stack trace, and what did your config file look like?

**Comment by ryancwalsh** [comment]
This issue is from Aug 2018, so obviously I don't remember everything that was happening then, but looking at the link, I think all I was recommending by creating this issue for you was for you to add some kind of guidance in the Readme related to this top part (and ignore the code part):

```
 * 1. Visit https://bitbucket.org/account/user/{your_username}/app-passwords
 * 2. Click "Create app password", and enable "Read" access to all of the following: "Account", "Issues", "Projects", "Repositories".
 *     When I tried granting access to just Issues, I got this misleading error: Symfony\Component\Debug\Exception\FatalThrowableError  : strtok() expects parameter 1 to be string, array given
```

Even though I didn't end up getting your library working, thanks for making it available. I see your name around a lot in the Laravel community and appreciate all that you provide.
