### ISSUE TITLE
Projects URL requires trailing slash.

### ISSUE THREAD

**Issue by bbrala** [BitbucketAPI/Client#15]
For some weird reason the `projects` url in the bitbucket api requires a trailing slash to function. Currently the package gives an 500 when requesting projects.

Check:
`https://api.bitbucket.org/2.0/teams/swisnl/projects` vs `https://api.bitbucket.org/2.0/teams/swisnl/projects/`

**Comment by GrahamCampbell** [comment]
Thanks. Related to https://github.com/BitbucketAPI/Client/pull/7?

**Comment by bbrala** [comment]
Yeah it is indeed. Some endpoints require a trailling slash... Atlassian is constent like that, and appearantly this is on other endpoint too. Ill send them a ticket, but i wouldnt hold your breath for them to fix this i fear.

**Comment by bbrala** [comment]
I've created a ticket on their service desk, perhaps being a paying customer helps :)

**Comment by GrahamCampbell** [comment]
Great. Let me know what they say. :)

**Comment by bbrala** [comment]
Yana Bazulina commented:

Hi Björn, 

Thank you for getting in touch with Bitbucket Support Team.

This is actually an expected behavior and by design,  the reason behind this is collections end point should have a trailing slash at the end, however individual end point resource doesn't. 

For reference: 

https://en.wikipedia.org/wiki/Representational_state_transfer#Applied_to_Web_services

 

Hope this helps and answers your question, let me know if you have any other questions or need help with anything else. 

Kind regards,

 

Yana

Bitbucket Cloud Senior Support Engineer

**Comment by GrahamCampbell** [comment]
Hmm, why do some of their endpoints break if you add a slash then?

**Comment by bbrala** [comment]
Which break WITH a trailing slash then?

**Comment by bbrala** [comment]
When i check `https://api.bitbucket.org/2.0/repositories/swisnl` i really only see endpoint where we look at a single record (sometimes) break with trailing slash, so for example `https://api.bitbucket.org/2.0/teams/swisnl/projects/DRUP/` breaks, but that is kinda what they say. 

The rest of the endpoints that list data seem to work with a slash.

**Comment by bbrala** [comment]
Well, they ended up saying

> Hi Bjorn, 
> 
> Thank you for the follow up. 
> 
> All those end points are calls to the individual repo, not the collection, those this reason the behavior is different. 
> 
> I agree with you about the consistency though, as it's not intuitive in one call to expect / and in another it's not required. 
> 
> If you do not mind, could you please raise a feature request here: 
> 
> https://bitbucket.org/site/master/issues
> 
> our Product team will review this functionality and make a decision if this is something we should change in the future. 
> 
> Thank you and let me know if I can help with anything else. 
> 
> Kind regards,
> 
> Yana
> 
> Bitbucket Cloud Senior Support Engineer 

So i made an issue on their public tracker. I'm guessing the only way to fix this is supply a way to tell the package which endpoints do or do not require trailing slashes :x

https://bitbucket.org/site/master/issues/17211/inconsistent-endpoints
