### ISSUE TITLE
Error on wrong wrong permissions error

### ISSUE THREAD

**Issue by martijn94** [BitbucketAPI/Client#16]
Hey,

Thanks for creating this!

The package throws an unhandled error when trying to make a request to a endpoint with insufficient permissions.

<img width="1281" alt="screen shot 2018-10-12 at 14 21 17" src="https://user-images.githubusercontent.com/1652861/46868917-584a1b00-ce2a-11e8-94ee-c96e78de5970.png">

Contents of $detail are: 

<img width="244" alt="screen shot 2018-10-12 at 14 23 33" src="https://user-images.githubusercontent.com/1652861/46868926-6bf58180-ce2a-11e8-92b9-6d8fbb254643.png">

Thanks.

**Comment by GrahamCampbell** [comment]
Thanks for the report. I'll look into this whenever I get a minute. 🍻

**Comment by GrahamCampbell** [comment]
A fix for this will be included in v1.1.1 and v2.0.0. Sorry this took so long for me to get around to!
