### ISSUE TITLE
Problems installing package

### ISSUE THREAD

**Issue by Bogardo** [BitbucketAPI/Client#18]
When running `composer require bitbucket/client` in an empty directory I get the following error:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bitbucket/client ^1.1 -> satisfiable by bitbucket/client[v1.1.0].
    - bitbucket/client v1.1.0 requires php-http/client-implementation ^1.0 -> no matching package found.
```

My System:

```
$ php --version

PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:47:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

```
$ composer --version

Composer version 1.8.0 2018-12-03 10:31:16
```

**Comment by GrahamCampbell** [comment]
Sorry the readme isn't clear. You also need to install a http client implementation, as per the error message:

>     - bitbucket/client v1.1.0 requires php-http/client-implementation ^1.0 -> no matching package found.

For example, using the Guzzle 6 HTTP client:

```bash
$ composer require require bitbucket/client php-http/guzzle6-adapter:^1.1
````

When you new up a new client, it will automatically search for a client to use, if none is specified:

https://github.com/BitbucketAPI/Client/blob/v1.1.0/src/Client.php#L78
https://github.com/BitbucketAPI/Client/blob/master/src/HttpClient/Builder.php#L85-L100

**Comment by Bogardo** [comment]
I did try installing the `php-http/guzzle6-adapter` but I didn't specify any version. Using `^1.1` does work.
Are you planning on updating the dependencies to support the newer versions?

**Comment by GrahamCampbell** [comment]
> Are you planning on updating the dependencies to support the newer versions?

The 1.x is pretty standard right now. Nobody else really supports 2.x yet.

**Comment by GrahamCampbell** [comment]
It's just a shame composer's require command doesn't get the correct version. It just blindly tries the latest major version.

**Comment by GrahamCampbell** [comment]
I've updated the readme to make things clearer.
