### ISSUE TITLE
How to get a single repo? e.g. call `GET /repositories/foo/bar`

### ISSUE THREAD

**Issue by fideloper** [BitbucketAPI/Client#21]
Hi!

The only way I see to get a specific repository is to use the repositories `list()` method (while the API provides a way to call a `GET` request on `/repositories/user/repo_slug`). I'm wondering if I'm wrong - do I need to do something like this, or is there another way?

```php
$repos = $client->repositories()
    ->users('fideloper')
    ->list(['q' => 'full_name="fideloper/my_repo"']);

return $repos['values'][0] ?? null;
```

Thanks!

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Does the show method not do what you want? :)

https://github.com/BitbucketAPI/Client/blob/v1.1.0/src/Api/Repositories/Users.php#L59-L72

**Comment by GrahamCampbell** [comment]
```php
return $client->repositories()
    ->users('fideloper')
    ->show('my_repo');
```

**Comment by fideloper** [comment]
Thank you!

**Comment by fideloper** [comment]
(Sorry I didn't see your first reply - I thought that would show the user itself, and not a user's repository).

**Comment by GrahamCampbell** [comment]
No. The API design of this package is basically curried. At each point, you are providing one more piece of information. You choose the repositories class at the start, then you provide the user, then the repo name. Bitbucket doesn't distinguish between users and teams quite in the same way that GitLab does. :)

**Comment by fideloper** [comment]
Gotcha - appreciate the explanation!
