### ISSUE TITLE
How can I perform auth with app password method?

### ISSUE THREAD

**Issue by Giacomo92** [BitbucketAPI/Client#26]
Hi everyone, how can I perform auth to Bitbucket with app password method?
I wrote this based on #14 

    $username = config('bitbucket.username');
    $c = new Client();
    $c->authenticate(
            Client::AUTH_HTTP_PASSWORD,
            $username, 
            config('bitbucket.password')
     );
    $reposResult = $c->currentUser()->show();`

When I try to run this, I get this message:
Bitbucket\Exception\ClientErrorException  : Unauthorized

Thank you for your help

**Comment by GrahamCampbell** [comment]
Yes, that will work unless you have two factor authentication enabled, in which case you will see an unauthorized error.

**Comment by GrahamCampbell** [comment]
App passwords should work, however.

**Comment by GrahamCampbell** [comment]
And what you typed there is the intended usage:

https://github.com/GrahamCampbell/Laravel-Bitbucket/blob/v5.2.0/src/Authenticators/PasswordAuthenticator.php#L26-L48

**Comment by GrahamCampbell** [comment]
If you are using Laravel, however, I'd recommend using my Laravel specific package: https://github.com/GrahamCampbell/Laravel-Bitbucket.

**Comment by Giacomo92** [comment]
Hi @GrahamCampbell , it was a permission error. I did not granted the read permission for the user api. However I will use https://github.com/GrahamCampbell/Laravel-Bitbucket as your advice.

Thank you

**Comment by GrahamCampbell** [comment]
I also just noticed that there is an example on the README: https://github.com/BitbucketAPI/Client#usage.
