### ISSUE TITLE
Are partial responses supported?

### ISSUE THREAD

**Issue by sbmthd** [BitbucketAPI/Client#29]
Is it possible to retrieve only specific fields in a response?

For example, using the 'fields' parameter as described in the official API docs - 

https://api.bitbucket.org/2.0/users/evzijst?fields=-links

I've tried a few things along the lines of -

... commits($identifier)->list(['pagelen' => 100, 'fields' => ['values.author', 'values.message', 'values.date', 'values.type']])

I expect I'm just doing something wrong, but not sure what!

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Does replacing `['values.author', 'values.message', 'values.date', 'values.type']` with `implode(',', ['values.author', 'values.message', 'values.date', 'values.type'])` work?

Example: https://api.bitbucket.org/2.0/users/evzijst?fields=display_name,uuid.

**Comment by sbmthd** [comment]
Hi Graham, I've tried your suggestion but unfortunately it doesn't work.

**Comment by GrahamCampbell** [comment]
Can you find out the raw HTTP request that the library is actually sending?

**Comment by GrahamCampbell** [comment]
Closing due to no response.
