### ISSUE TITLE
No support to query repositories on a workspace?

### ISSUE THREAD

**Issue by oppiansteve** [BitbucketAPI/Client#35]
Sorry, if I'm being stupid here, but it doesn't seem you support the workspace repositories query.
see https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D

Doing this seems to work fine, but shouldn't this be supported in the client itself?
```
class WorkspaceRepositories extends \Bitbucket\Api\Repositories {
    public function listWorkspace(string $workspace, array $params = [])
    {
        $path = $this->buildRepositoriesPath($workspace);

        return $this->get($path, $params);
    }
}
$workspace_repositories = new WorkspaceRepositories($c->getHttpClient());
print_r($workspace_repositories->listWorkspace('bitbucket'));
```

Am I missing something clever, or is this what I should do for now?

**Comment by GrahamCampbell** [comment]
This is already supported. Please use `->users($workspaceName)->list();`.
