### ISSUE TITLE
How can i get all branches for a repository? 

### ISSUE THREAD

**Issue by alexeightsix** [BitbucketAPI/Client#36]
I have this:

$test = $c->repositories()->users("xxx")->list()

which returns all the repositories

I want to be able to get all the branches from each repository

I also want to make sure I retrieve ALL repositories, I noticed there was a "page" and "next" key returned, how do i go to page 2?

**Comment by alexeightsix** [comment]
Figured out a solution!

**Comment by aaronbauman** [comment]
Can you share? I also need to go to next page, but for repositories

**Comment by GrahamCampbell** [comment]
You need to use the result pager, as documented on the README: https://github.com/BitbucketPHP/Client#example-3.
