### ISSUE TITLE
[2.1] DiffStats should be DiffStat without that 's'

### ISSUE THREAD

**Issue by codeit-ninja** [BitbucketAPI/Client#38]
The DiffStats class in DiffStats.php is creating a url like so 

`https://api.bitbucket.org/2.0/repositories/{workspace}/{repo}/diffstats/{spec}`

This will result into this

`"There is no API hosted at this URL. For information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"`

The solution is to remove the 's' in 'Users\DiffStats.php:49'.

**Comment by GrahamCampbell** [comment]
Thanks. This will be fixed in 2.1.4. :)
