### ISSUE TITLE
Missing filter for branches when retrieving commits

### ISSUE THREAD

**Issue by michastubi** [BitbucketAPI/Client#58]
Maybe I am missing something, but i think it is not possible to perform this request: 
```
GET /repositories/{workspace}/{repo_slug}/commits/master

Returns all commits on rev master (similar to git log master, hg log master).
```
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commits#get
Unfortanly i cannot find a way to add the name of the branch at the end of the url. Like decripted in the bitbucked api.

**Comment by GrahamCampbell** [comment]
`$client->repositories()->workspaces('workspace')->repos('repo_slug')->commits()->show('master')`?

**Comment by michastubi** [comment]
Hmm, it seems to me, that the class Workspaces doesn´t have a method called `repos()`? 
`-> Call to undefined method Bitbucket\Api\Repositories\Workspaces::repos()`
[https://github.com/BitbucketPHP/Client/blob/3.1/src/Api/Repositories/Workspaces.php](https://github.com/BitbucketPHP/Client/blob/3.1/src/Api/Repositories/Workspaces.php)

But it has a `commit(string $repo)` method, which I tried to use like this:
(I am using the Laravel Bitbucket Facade)
`Bitbucket::repositories()->workspaces('workspace')->commits('repo_slug')->list();`
-> Which is working quite fine to retrive all commits on my repository, but I can not find a way to specify the branch in the `Commits` Class.
[https://github.com/BitbucketPHP/Client/blob/3.1/src/Api/Repositories/Workspaces/Commits.php](https://github.com/BitbucketPHP/Client/blob/3.1/src/Api/Repositories/Workspaces/Commits.php)

**Comment by GrahamCampbell** [comment]
Oh, I meant `repositories`, not repos, sorry.

**Comment by GrahamCampbell** [comment]
I meant:

```php
$client->repositories()->workspaces('workspace')->commits('repo_slug')->show('master')
```

**Comment by michastubi** [comment]
Oh yeah, your right. I never tried to use the show method, because in the signiture of the method, the name of the parameter is `$commit`. Which was the reason, why I thought this method is used to show a single commit. Maybe renaming this, to `$branch` etc... would be a good idea?
Anyway thanks a lot for your help!

**Comment by vesper8** [comment]
@GrahamCampbell any chance you could provide an example on how to get the very last commit only on the master branch?

**Comment by GrahamCampbell** [comment]
Use the branches API.

**Comment by saurabh-ecsion** [comment]
> @GrahamCampbell any chance you could provide an example on how to get the very last commit only on the master branch?

@GrahamCampbell  any update on this ?
