### ISSUE TITLE
Document App Passwords

### ISSUE THREAD

**Issue by tacman** [BitbucketAPI/Client#60]
I'm not seeing the option for Personal Access Tokens on bitbucket.com:

![image](https://user-images.githubusercontent.com/619585/102909682-5850f700-4447-11eb-8d0d-997c7d7c7eb7.png)

After hunting around a bit, it seems that instead the correct process is to create an App Password, then log in with your own username and the app password.

I'll make a PR to the readme.

**Comment by GrahamCampbell** [comment]
Isn't this already documented at https://github.com/BitbucketPHP/Client#http-password? App passwords are a known concept used by many services, as "passwords".

**Comment by tacman** [comment]
Well, yes, but it took me an embarrassingly long time to figure it out.  I
thought that perhaps I needed a paid account on bitbucket.  And because I
used Google to authenticate my bitbucket account, I couldn't use a regular
password to even try the other method.

So yet, it's documented on that other site, but I got stuck trying to
authenticate.  It's working now, so I thought it would make it easier for
others that are new to this bundle and bitbucket's API.  Github's works
with the access tokens, which is what I was expecting.

Kudos on releasing version 4 of this excellent library!

Tac
