### ISSUE TITLE
Question asked by Michael Bagnall

### ISSUE THREAD

**Issue by GrahamCampbell** [BitbucketAPI/Client#62]
# Question

I am working on an app that utilizes your API for Bitbucket.

I am writing because I have a question. I am trying to pull a list of work spaces from a client. Seems straight forward enough, but I cannot seem to locate a method that does this in the 3.x branch (I am limited to the 3.x branch as I am using Drupal for the time being).

Am I overlooking something? If you have the opportunity and could point me in the right direction, I’d be greatly appreciative.

# Answer

> I am limited to the 3.x branch as I am using Drupal for the time being

Version 4 can be installed in a Drupal app too.

> I am trying to pull a list of work spaces from a client. 

What do you mean by this? Do you mean you watch to fetch all workspaces the currently authenticated user is a member of?

The following code will do that:

```php
$paginator = new Bitbucket\ResultPager($client);
$workspaces = $paginator->fetchAll($client->currentUser(), 'listWorkspaces', [['role' => 'member']]);
```

If there are a particularly large amount of workspaces, you can use the `fetchAllLazy` method instead of `fetchAll`, which returns an iterator which you can iterate over only once (and behind the scenes, it is chunking only a few in memory at once).

If you call `$client->currentUser()->listWorkspaces(['role' => 'member'])`, then you will only get the first page of results.

---

The question was asked by email, however Michael's mail server was not configured to accept incoming mail, so my reply was not delivered. Given that I have already written a reply, I will post it here.

**Comment by GrahamCampbell** [comment]
// cc @ElusiveMind

**Comment by ElusiveMind** [comment]
This was incredibly helpful! Thank you so much for pointing me in the right direction!



—
Michael. R. Bagnall
michael@bagnall.io
Web Solutions Architect
PHP, JavaScript, NodeJS, PHP, Drupal
Linux, Apache, Nginx, Docker, Rancher

LinkedIn <https://www.linkedin.com/in/mbagnall> | Resume <https://rb.gy/4azeva> | GitHub <https://github.com/ElusiveMind> | Bitbucket <https://bitbucket.org/mrbagnall/> | DockerHub <https://hub.docker.com/u/mbagnall> | NPM <https://www.npmjs.com/~mbagnall> | Drupal <https://www.drupal.org/u/elusivemind>
