### ISSUE TITLE
Missing Trailing Slash on Repository Environments Endpoint

### ISSUE THREAD

**Issue by Humni** [BitbucketAPI/Client#65]
Version: 4.0.0

The package is installed using the standard config. Requests URIs are being built without a trailing slash for some endpoints. For instance:

```
// Fetched using `dd(self::prepareUri($uri, $params));` at AbstractAPI.php:87 
/2.0/repositories/{workspace}/{repository}/environments
```

These result in an exception: `Bitbucket\Exception\RuntimeException: Resource not found: There is no API hosted at this URL.`

The URI should actually be:
```
/2.0/repositories/{workspace}/{repository}/environments/
```

Unfortunately, this is only an issue for some endpoints as some exclude the trailing slash, so a blanket addition of a trailing slash would break other endpoints such as:

```
/2.0/workspaces/{workspace}/pipelines-config/variables
```

**Comment by GrahamCampbell** [comment]
Yeh, tell me about it. Bitbucket's API is a mess! If you'd like to submit a PR to fix this, that'd be great. There should be some similar changes in the PRs/commit history for guidance. Otherwise, I'll get to this probably at the weekend.

**Comment by Humni** [comment]
@GrahamCampbell They really are! It shouldn't even have an impact but I guess that's Atlassian for ya.. 

As I only needed 2 endpoints for limited usage I've just gone to using Guzzle as I couldn't see a nice way to fix it quickly without introducing possible unintended issues. Thanks for the package nonetheless!
