### ISSUE TITLE
Pipeline Config URI should use a Hypen

### ISSUE THREAD

**Issue by Humni** [BitbucketAPI/Client#66]
Version: 4.0.0

Requests URIs are being built with an underscore instead of a hyphen. For instance:

```
// Fetched using `dd(self::prepareUri($uri, $params));` at AbstractAPI.php:87 
/2.0/workspaces/{workspace}/pipelines_config/variables
```

These result in an exception: `Bitbucket\Exception\RuntimeException: Resource not found: There is no API hosted at this URL.`

The URI should actually be:
```
/2.0/workspaces/{workspace}/pipelines-config/variables
```

**Comment by GrahamCampbell** [comment]
Bitbucket's documentation says it is with an underscore: https://developer.atlassian.com/bitbucket/api/2/reference/resource/.

**Comment by Humni** [comment]
@GrahamCampbell it's worse than that, it's only for some pipelines config endpoints (they use a mix) for some ungodly reason

![image](https://user-images.githubusercontent.com/5545538/111082293-5a20e700-856c-11eb-957b-7a899b7464c2.png)

**Comment by GrahamCampbell** [comment]
Oh, dear!
