### ISSUE TITLE
Cannot unpack array with string keys

### ISSUE THREAD

**Issue by saurabh-ecsion** [BitbucketAPI/Client#69]
Getting following error in function **fetch** 

File name: `vendor/bitbucket/client/src/ResultPager.php`

```
public function fetch(AbstractApi $api, string $method, array $parameters = []): array
    {
        /** @var mixed */
        $result = self::bindPerPage($api, $this->perPage)->$method(...$parameters);
 
        if (!\is_array($result)) {
            throw new RuntimeException('Pagination of this endpoint is not supported.');
        }
 
        $this->postFetch();
 
        return $result;
    }
```
 
Mainly in` $result = self::bindPerPage($api, $this->perPage)->$method(...$parameters);`

**Comment by GrahamCampbell** [comment]
You cannot call our code with an array with string keys. You must pass the parameters in order with numeric indexes.
