### ISSUE TITLE
Caching results

### ISSUE THREAD

**Issue by saurabh-ecsion** [BitbucketAPI/Client#70]
How can we cache result similar to https://github.com/KnpLabs/php-github-api/blob/master/doc/caching.md ?

**Comment by GrahamCampbell** [comment]
You can do exactly the same thing as in those docs. :)

**Comment by GrahamCampbell** [comment]
Well, almost. You need to call it on our http client builder: https://github.com/BitbucketPHP/Client/blob/4.0/src/HttpClient/Builder.php#L161.

**Comment by GrahamCampbell** [comment]
A full example is at https://github.com/GrahamCampbell/Laravel-Bitbucket/blob/v8.0.2/src/BitbucketFactory.php.
