### ISSUE TITLE
Is it possible to clone and pull repository via this package?

### ISSUE THREAD

**Issue by iboved** [BitbucketAPI/Client#71]
Hi!

Is it possible to clone and pull repository via this package? I want to use this package to update my private repositories.

The questions are:
1. How to clone specific repository?
2. How to pull specific repository in the specific branch?

Thanks a lot for the answers!

**Comment by GrahamCampbell** [comment]
No. You'll need to use `git` to do that. Bitbucket does have any API for making changes to the repositories, though, so you do have limited ability to do that.

**Comment by iboved** [comment]
@GrahamCampbell thanks for your answer. I will try to find the needed API.
