### ISSUE TITLE
"psr/cache": "^2.0|^3.0"

### ISSUE THREAD

**Issue by JellyBellyDev** [BitbucketAPI/Client#76]
Hi! 
It's possible to bump `psr/cache` like https://github.com/symfony/cache/blob/v6.0.2/composer.json#L25 ?

Thanks

**Comment by GrahamCampbell** [comment]
Support for v2 is coming later this month, but not v3.

**Comment by JellyBellyDev** [comment]
Thank you so much @GrahamCampbell!

**Comment by GrahamCampbell** [comment]
v1, v2 and v3 are now supported.

**Comment by JellyBellyDev** [comment]
🚀
