### ISSUE TITLE
Refresh tokens?

### ISSUE THREAD

**Issue by nasikshafeek** [BitbucketAPI/Client#8]
Hi @GrahamCampbell,
How can one go about refreshing the token when using oauth along-with your https://github.com/GrahamCampbell/Laravel-Bitbucket library?

(I get this message for almost every request: `Access token expired. Use your refresh token to obtain a new access token.`)

**Comment by razamoh** [comment]
@kisanme  : i have same problem ... really confusing , it works well with username and password. but not with oAuth. 
@GrahamCampbell  :)

**Comment by moebrowne** [comment]
Have you guys read the auth docs? The access token you get from OAuth expire after an hour but the `refresh_token` you get can be used indefinitely to get fresh access tokens.

https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication#refresh-tokens

**Comment by razamoh** [comment]
Yeah I know it.but how to get it using this package?@moebrowne

**Comment by moebrowne** [comment]
You can't. The API doesn't have any endpoints for auth that I'm aware of

**Comment by GrahamCampbell** [comment]
This package does not handle the auth2 flow stuff for you. That will need to be done manually, out side of this package.

**Comment by razamoh** [comment]
Thanks @GrahamCampbell

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Login is what I'm using to handle oauth2 with Bitbucket, but there exist others too.

**Comment by GrahamCampbell** [comment]
The actual refresh code is: https://github.com/AltThree/Login/blob/v5.0.0/src/LoginClient.php#L173.

**Comment by GrahamCampbell** [comment]
@razamoh With regards to your confused emoji reaction, not including the auth flow in this package was an intentional design decision, to separate responsibilities. There already exists loads of oauth2 clients.

**Comment by GrahamCampbell** [comment]
http://oauth2-client.thephpleague.com/ is a popular one.

**Comment by razamoh** [comment]
Thanks alot @GrahamCampbell .  :+1:
