### ISSUE TITLE
Filter issues by "state"?

### ISSUE THREAD

**Issue by ultimike** [BitbucketAPI/Client#80]
I'm trying to work out how to get a list of open issues for a project using something like this:

```
$issues = $this->client->repositories()
          ->workspaces($workspace)
          ->issues($project)
          ->list($params);
```

But I can't seem to find any documentation on allowable $params. I've found [this page](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-issue-tracker/#api-repositories-workspace-repo-slug-issues-get) on the Atlassian documentation, but it doesn't seem to be much help.

I'm trying to figure out how to only return open issues, and I'm pretty sure it has to do with passing in the proper $params...

-mike

**Comment by GrahamCampbell** [comment]
`issues()->list($params)` already supports this today via:

```
->list(['q' => 'state = "open"'])
```
