### ISSUE TITLE
Src not working as expected

### ISSUE THREAD

**Issue by saurabh-ecsion** [BitbucketAPI/Client#81]
I wanted to list of all files from specific branch.

So I did following 

```
$client->repositories()
            ->workspaces('abc')
            ->src('xyz')
            ->show('demo',"/");
```
**demo** is my branch name

Above code should return list of files as per documentation but it is not working.

Can you please help me out how can I get list of files?

**Comment by GrahamCampbell** [comment]
There is no such src function.

**Comment by antback** [comment]
hi @saurabh-ecsion,

Were you be able to list the files? I'm facing the same issue. I would like to do it recursively. 

Thanks!

**Comment by GrahamCampbell** [comment]
See https://github.com/BitbucketPHP/Client/pull/114.
